DotNetCore/Models/ErrorViewModel.cs
using System;

namespace DotNetCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DotNetCore/Controllers/BuyerTestController.cs
using DotNetNote.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetCore.Controllers
{
    public class BuyerTestController : Controller
    {
        private readonly IBuyerRepository buyerRepository;

        public BuyerTestController(IBuyerRepository buyerRepository)
        {
            this.buyerRepository = buyerRepository;
        }

        public IActionResult Index()
        {
            var buyers = buyerRepository.GetBuyers();
            return View(buyers);
        }

        public IActionResult Details(string buyerId)
        {
            var buyer = buyerRepository.GetBuyer(buyerId);
            return View(buyer);
        }
    }


}

DotNetCore/Controllers/CompaniesController.cs
using DotNetNote.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetCore.Controllers
{

    public class CompaniesController : Controller
    {
        //private readonly IConfiguration _configuration;
        private readonly ICompanyRepository _repository;

        //public CompaniesController(IConfiguration configuration, ICompanyRepository repository)
        public CompaniesController(ICompanyRepository repository)
        {
            //this._configuration = configuration;
            this._repository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string name)
        {
            ViewBag.Message = $"{name}을 입력했습니다.";

            return View();
        }

        [HttpGet]
        public IActionResult Manage()
        {
            var companies = _repository.Read();
            //return View();
            return View(companies);
        }

        [HttpPost]
        public IActionResult Manage(string name)
        {
            _repository.Add(new CompanyModel() { Name = name });
            //return View();
            return RedirectToAction(nameof(Manage));
        }


    }
}

DotNetCore/Controllers/DefaultApiController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace DotNetCore.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class DefaultApiController : ControllerBase
    {
        // GET: api/<DefaultApiController>
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/<DefaultApiController>/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }

        // POST api/<DefaultApiController>
        [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT api/<DefaultApiController>/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE api/<DefaultApiController>/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

DotNetCore/Controllers/DefaultMvcController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetCore.Controllers
{
    public class DefaultMvcController : Controller
    {
        // GET: DefaultMvcController
        public ActionResult Index()
        {
            return View();
        }

        // GET: DefaultMvcController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DefaultMvcController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DefaultMvcController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DefaultMvcController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DefaultMvcController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DefaultMvcController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DefaultMvcController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DotNetCore/Controllers/HomeController.cs
using DotNetCore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DotNetCore/Controllers/IdeaAppController.cs
using DotNetNote.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetCore.Controllers
{
    public class IdeaAppController : Controller
    {
        private readonly IIdeaRepository _repository;

        public IdeaAppController(IIdeaRepository repository)
        {
            this._repository = repository;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var ideas = _repository.GetAll();

            return View(ideas);
        }

        [HttpPost]
        public IActionResult Index(Idea model)
        {
            if (ModelState.IsValid)
            {
                model = _repository.Add(model);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
        }

    }
}

DotNetCore/Views/BuyerTest/Index.cshtml
@model List<Buyer>
@{
    ViewData["Title"] = "Index";
}

<h2>BuyerTest/Index</h2>

<ul>
    @foreach (var buyer in Model)
    {
        <li>

            @buyer.BuyerId - @buyer.BuyerName - @buyer.BuyerCode

        </li>
    }
</ul>

DotNetCore/Views/Companies/Index.cshtml
<h1>회사들</h1>

<h2>입력</h2>
<form action="/Companies/Index" method="post">
    회사명:
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" name="name" id="name" />
        <label class="mdl-textfield__label" for="name">Name...</label>
    </div>
    <input class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored"
           type="submit" name="btnSubmit" value="전송" />
</form>

<h2>출력</h2>
<table class="mdl-data-table mdl-js-data-table" style="width: 200px;">
    <thead>
        <tr>
            <th class="mdl-data-talbe__cell--non-numeric">번호</th>
            <th class="mdl-data-talbe__cell--non-numeric">회사명</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td class="mdl-data-talbe__cell--non-numeric">Foo 회사</td>
        </tr>
        <tr>
            <td>2</td>
            <td class="mdl-data-talbe__cell--non-numeric">Bar 회사</td>
        </tr>
    </tbody>
</table>

@if (ViewBag.Message != null)
{
    <hr />
    @ViewBag.Message
}

DotNetCore/Views/Companies/Manage.cshtml
@model List<DotNetNote.Models.CompanyModel>


<h1>/Companies/Manage</h1>

<form action="/Companies/Manage" method="post">
    회사명:
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" name="name" id="name" />
        <label class="mdl-textfield__label" for="name">Name...</label>
    </div>
    <input class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored"
           type="submit" name="btnSubmit" value="전송" />
</form>

<table class="mdl-data-table mdl-js-data-table" style="width: 200px;">
    <thead>
        <tr>
            <th class="mdl-data-talbe__cell--non-numeric">번호</th>
            <th class="mdl-data-talbe__cell--non-numeric">회사명</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var c in Model)
        {
            <tr>
                <td>@c.Id</td>
                <td class="mdl-data-talbe__cell--non-numeric">@c.Name</td>
            </tr>
         }
    </tbody>
</table>

DotNetCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DotNetCore/Views/IdeaApp/Index.cshtml
@model List<Idea>

<h1>아이디어 관리자</h1>
<ul>
    @foreach (var idea in Model)
    {
<li>
    @idea.Id - @idea.Note
</li>}
</ul>

<form action="/IdeaApp/Index" method="post">
    <input type="text" name="Note" />
    <input type="submit" value="아이디어 저장" />
</form>

DotNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DotNetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    @* material 디자인 https://getmdl.io/  *@
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DotNetCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="dropdown nav-item">
                            <a class="dropdown-toggle nav-link text-dark" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                실습
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-area="" asp-controller="Companies" asp-action="Manage">Companies</a>
                                <a class="dropdown-item" asp-area="" asp-controller="IdeaApp" asp-action="Index">IdeaApp</a>
                                <a class="dropdown-item" asp-area="" asp-controller="BuyerTest" asp-action="Index">BuyerTest</a>
                            </div>
                        </li>
                    </ul>
                    
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DotNetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>